### ISSUE TITLE
Allow specifying which validation rules you want

### ISSUE THREAD

**Issue by stubailo** [apollostack/eslint-plugin-graphql#10]
Override this list: https://github.com/apollostack/eslint-plugin-graphql/blob/117097fb9a843647869ac724b9cb7b9a57c77cad/src/index.js#L21

**Comment by dguillamot** [comment]
@stubailo Was thinking it might be nice to be able to catch where we are pulling in fields in a Relay query, but are not using them in the attached view. So, let's say I am pulling users name, email, birth date via Relay, and displaying them in the view associated with my relay container. Then a few days later I remove the birth date from the view. So that relay data is not being used. I wondered if it would be possible to get a warning for that, similar to http://eslint.org/docs/rules/no-unused-vars

**Comment by stubailo** [comment]
Whoa, doing linting between the query and the actual code would be next-level. I wonder what that would be like.

**Comment by Globegitter** [comment]
Ha man, yeah that would would be amazing!
